// Barrel export file for content module
// This allows imports like: import { getHeroContent, BlogPost } from '@/lib/content'

// Type exports
export type {
  BaseContent,
  BlogPost,
  BlogCategory,
  HelpArticle,
  HelpSection,
  HeroContent,
  HeroStat,
  HeroCTAs,
  HeroImage,
  HeroImages,
  ProblemContent,
  ProblemStat,
  Testimonial,
  TestimonialAuthor,
  OutcomeContent,
  OutcomeCard,
  OutcomeCTA,
  NumbersContent,
  NumberStat,
  BentoSectionContent,
  DarkBentoSectionContent,
  BentoCard,
  BlindSalesSectionContent,
  BlindSalesProblem,
  SecuritySectionContent,
  SecurityFeature,
  FeatureSectionContent,
  FeatureTab,
  IntegrationsSectionContent,
  IntegrationCategory,
  Integration,
  PricingPageContent,
  PricingTier,
  PricingFeature,
  PricingHighlight,
  PricingHeader,
  PricingTestimonial,
  PricingFAQ,
  NavbarProduct,
  NavbarFeature,
  NavbarBenefit,
  NavbarLink,
  NavbarProductsContent,
  NavbarLinksContent,
  FooterContent,
  FooterSection,
  FooterLink,
  FooterCTA,
  FooterSocial,
  UseCasePageContent,
  UseCaseHero,
  UseCaseChallenge,
  UseCaseStat,
  UseCaseFeature,
  UseCaseSolution,
  UseCaseSolutionFeature,
  UseCaseImpact,
  UseCaseBottomCTA,
  ProductPageContent,
  ProductHero,
  ProductFeature,
  ProductShowcase,
  ProductBottomFeature,
  ProductBottomFeaturePoint,
  QBRIntroduction,
  QBRBestPractices,
  QBRBestPracticeRow,
  QBRCROImperative,
  QBRSummary,
  QBRSummaryPrinciple,
  QBRComparisonRow,
  BenefitGroupContent,
  BenefitGroupHero,
  BenefitGroupProblems,
  BenefitGroupProblemCard,
  BenefitGroupStats,
  BenefitGroupStat,
  BenefitGroupFeatures,
  BenefitGroupFeature,
  BenefitGroupHowItWorks,
  BenefitGroupWorkflowStep,
  BenefitGroupTestimonial,
  BenefitGroupComparison,
  BenefitGroupComparisonColumn,
  BenefitGroupComparisonRow,
  BenefitGroupWhoItsFor,
  BenefitGroupWhoItsForCard,
  BentoItem,
  BentoProps,
  ComparisonPageContent,
  ComparisonHero,
  ComparisonItem,
  ComparisonSection,
  ComparisonScenario,
  ComparisonAnalysis,
  ComparisonBenefits,
} from './types';

// Loader utilities (exported for advanced use cases)
export { loadYAML, getContentFromPath, getSingleContent, getMDXContent, CONTENT_ROOT, BLOG_PATH, HELP_PATH } from './loaders';

// Blog functions
export {
  getAllBlogPosts,
  getBlogPost,
  getBlogPostContent,
  getFeaturedPosts,
  getPosts,
  getPostsCount,
  getCategories,
  getPostsForFeed,
} from './blog';

// Help functions
export {
  getAllHelpArticles,
  getHelpArticle,
  getHelpArticleContent,
  getHelpSections,
  getHelpArticlesBySection,
  getHelpArticlesByTag,
  getHelpTags,
} from './help';

// Page content functions
export {
  getHeroContent,
  getProblemContent,
  getOutcomeContent,
  getNumbersContent,
  getBentoSectionContent,
  getDarkBentoSectionContent,
  getBlindSalesSectionContent,
  getSecuritySectionContent,
  getFeatureSectionContent,
  getIntegrationsSectionContent,
  getPricingPageContent,
  getFooterContent,
  getUseCaseContent,
  getProductContent,
  getProductsByBenefit,
  getAllProductsGroupedByBenefit,
  getQBRIntroduction,
  getQBRBestPractices,
  getQBRSummary,
  getNavbarProducts,
  getNavbarLinks,
  getBenefitGroupContent,
  getComparisonPageContent,
} from './pages';
