allProducts:
  name: "All Products"
  href: "/product"
  description: "View our complete product suite"
  icon: "/icons/all-products.svg"

products:
  - name: "AI Revenue Forecasting"
    href: "/product/revenue-analytics"
    description: "Track pipeline, forecasts, and sales velocity. Make data-driven decisions to meet revenue goals"
    icon: "/icons/revenue-analytics.svg"

  - name: "Guided Selling"
    href: "/product/guided-selling"
    description: "AI-driven insights on deal health, customer sentiment, and next steps and competition"
    icon: "/icons/guided-selling.svg"

  - name: "Team Insights"
    href: "/product/team-insights"
    description: "Monitor team performance, and identify find coaching needs, for better sales outcomes"
    icon: "/icons/team-insights.svg"

  - name: "Customer 360"
    href: "/product/customer-360"
    description: "All customer interactions, contacts, and documents in one place for faster collaboration"
    icon: "/icons/customer-360.svg"
